version: '3.2'

services:

  substrate-interface-api:
    build: substrate-interface-api/.
    image: substrate-interface-api
    ports:
      - '8000:8000'
    volumes:
      - './substrate-interface-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=prod
      - TYPE_REGISTRY=polkadot
      - SUBSTRATE_ADDRESS_TYPE=0
      - SUBSTRATE_RPC_URL=http://substrate-node:9933/
    depends_on:
      - substrate-node
      - redis

  substrate-node:
    image: polkasource/substrate-client:polkadot-latest
    hostname: substrate-node
    volumes:
      - 'substrate-data:/data'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --rpc-external --ws-external --rpc-cors=all --pruning=archive

  redis:
    image: redis:3.2.11

  substrate-interface-gui:
    image: substrate-interface-gui:latest
    build:
      context: substrate-interface-gui/.
      args:
        SUBSTRATE_API_URL: http://localhost:8001/rpc/

    ports:
      - '8001:80'
    depends_on:
      - substrate-interface-api

volumes:
  substrate-data:
